PRODUCT_NOT_FOUND = 'Product not found'
MESSAGE='message'
BRAND_NOT_FOUND = 'Brand not found'
HTTP_API_ERROR = 111
HTTP_200_SUCCESS=200
REQUEST_SUCCESSFULL="Successfully Updated!"
CREATED_SUCCESSFULL="Successfully Created!"
DELETED_SUCCESSFULL="Successfully Deleted!"
SUCCESS="success"
DOES_NOT_EXIST = "{0} does not exist"
UNIQUE_CONTACT_EMAIL= "Contact email should be unique"
UNIQUE_BRAND_NAME = "Brand with this name already exists"
UNIQUE_PRODUCT_NAME = "Product with this name already exists"
UNIQUE_PRODUCT_VARIANT_NAME="Product variant with this name already exists"
